version: '3.8'
services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    volumes:
      - ./quotes.txt:/app/quotes.txt
      - ./downloads:/app/downloads
